name: "scan2html"
version: "0.5.3"
maintainer: anill1
repository: github.com/anill1/scan2html
summary: A Trivy plugin that scans and outputs the results to a single page app.
usage: A Trivy plugin that scans and outputs the results to a single page app.
description: |-
  A Trivy plugin that scans and outputs the results (vulnerabilities, misconfigurations, secrets, SBOM in containers, Kubernetes, code repositories, clouds and more) to a single page app.
  trivy scan2html [-h,--help] command target filename
platforms:
  - selector:
      os: windows
    uri: https://github.com/anill1/scan2html/releases/download/v0.5.3/scan2html.tar.gz
    bin: ./scan2html.sh
  -
    uri: https://github.com/anill1/scan2html/releases/download/v0.5.3/scan2html.tar.gz
    bin: ./scan2html.sh
